"""Light-weight LLM client abstraction for the MVP.

The implementation prefers a real ``litellm`` backend so that the generator
and reviewer can call an actual hosted model.  When an API key or the
package itself is unavailable the client transparently falls back to a
stub that keeps the rest of the pipeline runnable for dry-runs/tests.
"""
from __future__ import annotations

import logging
import json
import os
from typing import Any, Dict, List, Optional

from common.config import DecodingProfile, get_openai_api_key

try:  # pragma: no cover - optional dependency
    from litellm import completion as litellm_completion
except Exception:  # pragma: no cover - optional dependency
    litellm_completion = None


LOGGER = logging.getLogger("common.llm")


class LLMConfigError(RuntimeError):
    """Raised when a real LLM call is requested but not properly configured."""


class LLMClient:
    """Small wrapper over litellm with a deterministic fallback."""

    def __init__(
        self,
        model_name: str,
        decoding: DecodingProfile,
        use_stub_when_unavailable: bool = True,
    ) -> None:
        self.model_name = model_name
        self.decoding = decoding
        self.use_stub = False
        self._fallback_on_error = use_stub_when_unavailable
        self._last_usage: Optional[Dict[str, Any]] = None

        api_key = (
            get_openai_api_key()
            or os.environ.get("OPENAI_API_KEY")
            or os.environ.get("VUL_LLM_API_KEY")
        )
        if api_key and not os.environ.get("OPENAI_API_KEY"):
            # litellm defaults to OPENAI_API_KEY for OpenAI-compatible endpoints.
            os.environ["OPENAI_API_KEY"] = api_key

        if litellm_completion is None or not api_key:
            msg = "litellm or VUL_LLM_API_KEY is missing; falling back to stub"
            if use_stub_when_unavailable:
                LOGGER.warning(msg)
                self.use_stub = True
            else:  # pragma: no cover - configuration error path
                raise LLMConfigError(msg)

    @property
    def last_usage(self) -> Optional[Dict[str, Any]]:
        """Return SDK usage metadata from the previous call."""

        return self._last_usage

    def generate(self, messages: List[Dict[str, str]], *, tools: Optional[List[Dict[str, Any]]] = None) -> str:
        """Generate a response from the underlying model or stub."""

        if self.use_stub:
            return self._stub_response(messages)

        assert litellm_completion is not None  # for type-checkers
        payload: Dict[str, Any] = {
            "model": self.model_name,
            "messages": messages,
            **self.decoding.to_kwargs(),
        }
        if tools:
            payload["tools"] = tools

        LOGGER.debug("Invoking litellm with payload keys: %s", list(payload))
        try:
            response = litellm_completion(**payload)  # pragma: no cover - network call
            self._last_usage = getattr(response, "usage", None)
            return response["choices"][0]["message"]["content"]
        except Exception as exc:  # pragma: no cover - network failure fallback
            if not self._fallback_on_error:
                raise
            LOGGER.warning("LLM call failed (%s); falling back to stub output", exc)
            self.use_stub = True
            return self._stub_response(messages)

    def _stub_response(self, messages: List[Dict[str, str]]) -> str:
        """Return a deterministic stub when the real model is unavailable."""

        prompt_echo = "\n---\n".join(m.get("content", "") for m in messages if m.get("content"))
        lowered = prompt_echo.lower()

        # Some call sites require strict JSON (Researcher / LLM verifier).
        if "researcher_report" in lowered and "produce only compact json" in lowered:
            payload = {
                "vuln_id": "UNKNOWN",
                "intent": "llm stub: offline researcher report",
                "preconditions": [],
                "tech_stack_candidates": [],
                "minimal_repro_steps": [],
                "references": [],
                "pocs": [],
                "deps": [],
                "risks": [],
                "verification_spec": {
                    "success_mode": "text",
                    "success_text_markers": ["Exploit SUCCESS"],
                    "flag_mode": "none",
                    "assertion_program": [{"op": "contains", "string": "Exploit SUCCESS"}],
                },
                "notes": "This report was generated by the built-in LLM stub due to unavailable network/keys.",
            }
            return json.dumps(payload, ensure_ascii=False)

        if "generator_manifest" in lowered and "produce only compact json" in lowered:
            # Synthesis callers already implement their own deterministic fallback
            # manifest builder. Return a non-JSON stub without curly braces so
            # the downstream parser reliably triggers that fallback.
            return "[llm-stub-synthesis] LLM unavailable; using deterministic fallback manifest."

        if "verification analyst" in lowered and "reply with strict json" in lowered:
            payload = {
                "verify_pass": False,
                "confidence": "low",
                "rationale": "LLM stub: unable to reach configured model endpoint.",
                "proposed_assertions": [],
                "extracted_evidence": [],
                "metamorphic": None,
            }
            return json.dumps(payload, ensure_ascii=False)

        return (
            "[llm-stub-response]\n"
            "The real LLM backend is not available (network/config). "
            "Returning deterministic guidance output.\n\n"
            f"Prompt digest (truncated):\n{prompt_echo[:400]}..."
        )
